server:
  port: 7000
  

  
spring:  
  datasource:
    url: jdbc:mysql://localhost:3306/product-db
    username: root
    password: root  
 
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    

#  
    
# spring.jpa.properties.hibernate.dialect
# spring.application.name= product-management  


